# chi-square test
this score should be used to evaluate categorical variables in a classification task

In [35]:
import seaborn as sns
df=sns.load_dataset('titanic')

In [36]:
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [37]:
df = df[['sex','embarked','alone','pclass','survived']]

In [38]:
df.head()

sex embarked  alone  pclass  survived
0    male        S  False       3         0
1  female        C  False       1         1
2  female        S   True       3         1
3  female        S  False       1         1
4    male        S   True       3         0

In [39]:
# Before applying chi-square test do label encoding

In [40]:
# label encoding
import numpy as np
df['sex'] = np.where(df['sex']=='male',1,0)

In [41]:
# from sklearn.preprocessing import LabelEncoder
# le = LabelEncoder()
# le.fit(df['embarked'])
# le
ordinal_label = {k:i for i ,k in enumerate(df['embarked'].unique(),0)}
df['embarked'] =df['embarked'].map(ordinal_label)

In [42]:
# df['embarked'] =le.transform(df['embarked'])

In [43]:
df['alone'] = np.where(df['alone'] == True,1,0)

In [44]:
df.head()

sex  embarked  alone  pclass  survived
0    1         0      0       3         0
1    0         1      0       1         1
2    0         0      1       3         1
3    0         0      0       1         1
4    1         0      1       3         0

In [47]:
# train test split is usually done to avoid overfitting 
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(df[['sex','embarked','alone','pclass']],df['survived'],test_size=0.3,random_state=101) 

In [48]:
x_train.head()

sex  embarked  alone  pclass
520    0         0      1       1
510    1         2      1       3
446    0         0      0       2
2      0         0      1       3
691    0         1      0       3

In [52]:
## perform chi -squre test
## chi2 return two values
# p value and f score
from sklearn.feature_selection import chi2

f_p_values = chi2(x_train,y_train)

In [55]:
f_p_values[0]

array([68.02020611, 10.86691227,  9.64404324, 20.13531511])

In [57]:
f_score = f_p_values[0]
p_values =f_p_values[1]

In [58]:
# the more f score the more important my feature is
f_score


array([68.02020611, 10.86691227,  9.64404324, 20.13531511])

In [60]:
# the lesser the p-value the more important the feature is
p_values

array([1.61828662e-16, 9.78976136e-04, 1.89966619e-03, 7.21520718e-06])

In [66]:
import pandas as pd
pval=pd.Series(p_values)
pval.index = x_train.columns

In [69]:
pval.sort_index(ascending = False)

sex         1.618287e-16
pclass      7.215207e-06
embarked    9.789761e-04
alone       1.899666e-03
dtype: float64